_admin_home:
    pattern:  /
    defaults: { _controller: WmaReisebueroAdminBundle:Default:index }
    
_admin_login: 
  resource: "@WmaReisebueroAdminBundle/Controller/LoginController.php"
  type: annotation
  prefix: /login
    
_reisen: 
  resource: "@WmaReisebueroAdminBundle/Controller/ReisenController.php"
  type: annotation
  prefix: /reisen
  
_kategorien: 
  resource: "@WmaReisebueroAdminBundle/Controller/KategorienController.php"
  type: annotation
  prefix: /kategorien
  
_regionen: 
  resource: "@WmaReisebueroAdminBundle/Controller/RegionenController.php"
  type: annotation
  prefix: /regionen
