_admin_home:
    pattern:  /
    defaults: { _controller: WmaReisebueroAdminBundle:Default:index }
    
_reisen: 
  resource: "@WmaReisebueroAdminBundle/Controller/ReisenController.php"
  type: annotation
  prefix: /reisen
  
_kategorien: 
  resource: "@WmaReisebueroAdminBundle/Controller/KategorienController.php"
  type: annotation
  prefix: /kategorien
