security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Wma\ReisebueroBundle\Entity\Benutzer: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
                
    providers:
        default_provider:
            entity: { class: Wma\ReisebueroBundle\Entity\Benutzer, property: benutzername }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            anonymous: ~
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
        
        admin: 
            pattern: ^/admin/
            anonymous: ~
            form_login:
              login_path: /admin/login
              check_path: /admin/login/check
            logout: 
              path: /admin/login/logout
              target: /admin/login

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
