<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110606164235 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE reisen ADD kategorie_id INT DEFAULT NULL, ADD region_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE reisen ADD FOREIGN KEY (kategorie_id) REFERENCES kategorien(id)");
        $this->addSql("ALTER TABLE reisen ADD FOREIGN KEY (region_id) REFERENCES regionen(id)");
        $this->addSql("CREATE INDEX IDX_4E34869BAF991D3 ON reisen (kategorie_id)");
        $this->addSql("CREATE INDEX IDX_4E3486998260155 ON reisen (region_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE reisen DROP kategorie_id, DROP region_id");
        $this->addSql("ALTER TABLE reisen DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE reisen DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_4E34869BAF991D3 ON reisen");
        $this->addSql("DROP INDEX IDX_4E3486998260155 ON reisen");
    }
}
