<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110606131720 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE reisen (id INT AUTO_INCREMENT NOT NULL, titel VARCHAR(255) DEFAULT NULL, preis NUMERIC(10, 0) DEFAULT NULL, kurzbeschreibung LONGTEXT NOT NULL, beschreibung LONGTEXT NOT NULL, beginn DATE DEFAULT NULL, ende DATE DEFAULT NULL, bild VARCHAR(255) NOT NULL, thumbnail VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_4E3486983287B86 (titel), PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE reisen");
    }
}
