<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110608145924 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE UNIQUE INDEX UNIQ_4A226A455E237E06 ON kategorien (name)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_4086D2DA5E237E06 ON regionen (name)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_4A226A455E237E06 ON kategorien");
        $this->addSql("DROP INDEX UNIQ_4086D2DA5E237E06 ON regionen");
    }
}
